### ISSUE TITLE
Clean up collate config

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#122]
The various collate configuration options are a hellacious mess (thanks to @aidanheerdegen) and should be cleaned up. There should be a top level `collate` `dict` with all `collate_mem` style options becoming sub-options of `collate`, like so:

```yaml
collate:
       enable: true
       mem: 8GB
       queue: express
```
